# https://taskfile.dev

version: "3"

tasks:
  test-unique-id:
    cmds:
      - task: build
        vars:
          FILE_PATH: unique-id
      - maelstrom test -w unique-ids --bin ./build/unique-id --time-limit 30 --rate 100000 --node-count 100 --availability total --nemesis partition

  test-broadcast-a:
    cmds:
      - task: build
        vars:
          FILE_PATH: broadcast/a
      - maelstrom test -w broadcast --bin ./build/broadcast/a --node-count 1 --time-limit 20 --rate 10

  test-broadcast-b:
    cmds:
      - task: build
        vars:
          FILE_PATH: broadcast/b
      - maelstrom test -w broadcast --bin ./build/broadcast/b --node-count 5 --time-limit 20 --rate 10

  test-broadcast-c:
    cmds:
      - task: build
        vars:
          FILE_PATH: broadcast/c
      - maelstrom test -w broadcast --bin ./build/broadcast/c --node-count 5 --time-limit 20 --rate 10 --nemesis partition

  test-broadcast-d:
    cmds:
      - task: build
        vars:
          FILE_PATH: broadcast/d
      - maelstrom test -w broadcast --bin ./build/broadcast/d --node-count 25 --time-limit 20 --rate 100 --latency 100 --nemesis partition

  test-broadcast-e:
    cmds:
      - task: build
        vars:
          FILE_PATH: broadcast/e
      - maelstrom test -w broadcast --bin ./build/broadcast/e --node-count 25 --time-limit 20 --rate 100 --latency 100 --nemesis partition

  build:
    internal: true
    cmds:
      - go build -o build/{{.FILE_PATH}} ./{{.FILE_PATH}}/main.go

  test-all:
    cmds:
      - task: test-unique-id
      - task: test-broadcast-a
      - task: test-broadcast-b
